---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "DevOpstestgroup"
    vm_name: testvm
    location: westus
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: "*"
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      virtual_network: "{{ vm_name }}"
      subnet: "{{ vm_name }}"
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBjj4eixU9Ylhtx/yTMk5iZu5x60azYq9wr2rFxsWN2DuGOtBL3lxdBXhh1yoNKiiDyVATKvfHzTUVPIKyGqS5kX0BTu7kdtjgExJqsTHPVTZjH8WLyVe/CiQLovMde0g2qncFoYrllVHYQf0D/jQXj2nanwICwjxxsnwk8cw3s23fp5QL1Zvebx7yGEDTsE2QAS+jVbQyNlRiv+1LhU4tl9OzJ1oFsKT8NMZLbW92aiIDO5xL73WEhLZnFq7Mo9ATXcUXmQIMxLldHRQKc3mPcCOAwRWe3WCxt1fZ54pDVSefXZxppYa8GwIibV20MnXUUiALbkjPlOak7rZV79lH azureuser@Jenkins-Slave"
      network_interfaces: "{{ vm_name }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest